### ISSUE TITLE
请问配置的数据库的初始化sql有吗

### ISSUE THREAD

**Issue by lyt23** [zhaoml529/SpringMVC-Activiti-Shiro#2]

**Comment by zhaoml529** [comment]
这个没用，用SpringOA，和这个一样。

**Comment by leglory** [comment]
其他错误：org.apache.shiro.authc.AuthenticationException

**Comment by zhaoml529** [comment]
这个项目是临时搭的架子，框架结构和我库中的SpringOA项目是一样的，可以Fork SpringOA。
